########################################
# Goals request
########################################
std_msgs/Header header
uint8[] id
bool enable
---
########################################
# Respones
########################################
bool result
